---

  - name: copy compose file
    copy:
      src: compose.yaml
      dest: /home/student/test_lab/compose.yaml
  
  - name: run docker-compose
    shell:
      cmd: "docker-compose up -d"
      chdir: /home/student/test_lab
    register: output
  - name: print result
    debug:
      var: output
