---

  - name: copy backend files
    copy:
      src: "{{ item.src }}"
      dest: /home/student/test_lab/backend
    loop:
      - src: Dockerfile
      - src: go.mod
      - src: go.sum
      - src: main.go
